name: chill-movie-app-4

services:
  chill-movie-app-4: #[=== Change It ===]
    image: ardidafa/chill-movie-apps-4:latest #[=== Change It ===]
    container_name: chill-movie-app-4 #[=== Change It ===]
    restart: unless-stopped
    ports:
      - "3005:80"  # Menghindari konflik dengan Nginx di host yang menggunakan port 80 [=== Change It ===]
    networks:
      - web
    environment:
      - NODE_ENV=production

networks:
  web:
    driver: bridge